/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ChargingHistoryResponse,
  chargingHistoryResponseSchema,
} from '../models/chargingHistoryResponse.js';
import {
  ChargingSessionsResponse,
  chargingSessionsResponseSchema,
} from '../models/chargingSessionsResponse.js';
import { string, unknown } from '../schema.js';
import { BaseController } from './baseController.js';

export class ChargingController extends BaseController {
  /**
   * Returns the paginated charging history for the authenticated account.
   *
   * @return Response from the API call
   */
  async getChargingHistory(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ChargingHistoryResponse>> {
    const req = this.createRequest('GET', '/api/1/dx/charging/history');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(chargingHistoryResponseSchema, requestOptions);
  }

  /**
   * Returns a charging invoice PDF for a charging session.
   *
   * @param id Charging session invoice identifier
   * @return Response from the API call
   */
  async getChargingInvoice(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/1/dx/charging/invoice/${mapped.id}`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * Returns charging session information. Only available for business fleet owners.
   *
   * @return Response from the API call
   */
  async getChargingSessions(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ChargingSessionsResponse>> {
    const req = this.createRequest('GET', '/api/1/dx/charging/sessions');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(chargingSessionsResponseSchema, requestOptions);
  }
}
