/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { BackupRequest, backupRequestSchema } from '../models/backupRequest.js';
import {
  BackupResponse,
  backupResponseSchema,
} from '../models/backupResponse.js';
import {
  CalendarHistoryResponse,
  calendarHistoryResponseSchema,
} from '../models/calendarHistoryResponse.js';
import {
  ChargeHistoryResponse,
  chargeHistoryResponseSchema,
} from '../models/chargeHistoryResponse.js';
import {
  GenericUpdateResponse,
  genericUpdateResponseSchema,
} from '../models/genericUpdateResponse.js';
import { Kind, kindSchema } from '../models/kind.js';
import {
  KindGetWallConnectorChargingHistory,
  kindGetWallConnectorChargingHistorySchema,
} from '../models/kindGetWallConnectorChargingHistory.js';
import {
  LiveStatusResponse,
  liveStatusResponseSchema,
} from '../models/liveStatusResponse.js';
import {
  OffGridVehicleChargingReserveRequest,
  offGridVehicleChargingReserveRequestSchema,
} from '../models/offGridVehicleChargingReserveRequest.js';
import {
  OperationRequest,
  operationRequestSchema,
} from '../models/operationRequest.js';
import {
  ProductsResponse,
  productsResponseSchema,
} from '../models/productsResponse.js';
import {
  SiteInfoResponse,
  siteInfoResponseSchema,
} from '../models/siteInfoResponse.js';
import {
  StormModeRequest,
  stormModeRequestSchema,
} from '../models/stormModeRequest.js';
import {
  TimeOfUseSettingsRequest,
  timeOfUseSettingsRequestSchema,
} from '../models/timeOfUseSettingsRequest.js';
import { optional, string, unknown } from '../schema.js';
import { BaseController } from './baseController.js';

export class EnergyController extends BaseController {
  /**
   * @param energySiteId
   * @param body
   * @return Response from the API call
   */
  async adjustSiteSBackupReserve(
    energySiteId: string,
    body: BackupRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BackupResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      energySiteId: [energySiteId, string()],
      body: [body, backupRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/energy_sites/${mapped.energySiteId}/backup`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(backupResponseSchema, requestOptions);
  }

  /**
   * @param energySiteId
   * @param kind
   * @param startDate
   * @param endDate
   * @param period
   * @param timeZone
   * @return Response from the API call
   */
  async getBackupOrEnergyHistory(
    energySiteId: string,
    kind: Kind,
    startDate: string,
    endDate: string,
    period?: string,
    timeZone?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CalendarHistoryResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      energySiteId: [energySiteId, string()],
      kind: [kind, kindSchema],
      startDate: [startDate, string()],
      endDate: [endDate, string()],
      period: [period, optional(string())],
      timeZone: [timeZone, optional(string())],
    });
    req.query('kind', mapped.kind);
    req.query('start_date', mapped.startDate);
    req.query('end_date', mapped.endDate);
    req.query('period', mapped.period);
    req.query('time_zone', mapped.timeZone);
    req.appendTemplatePath`/api/1/energy_sites/${mapped.energySiteId}/calendar_history`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(calendarHistoryResponseSchema, requestOptions);
  }

  /**
   * @param energySiteId
   * @param kind
   * @param startDate
   * @param endDate
   * @param timeZone
   * @return Response from the API call
   */
  async getWallConnectorChargingHistory(
    energySiteId: string,
    kind: KindGetWallConnectorChargingHistory,
    startDate: string,
    endDate: string,
    timeZone?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ChargeHistoryResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      energySiteId: [energySiteId, string()],
      kind: [kind, kindGetWallConnectorChargingHistorySchema],
      startDate: [startDate, string()],
      endDate: [endDate, string()],
      timeZone: [timeZone, optional(string())],
    });
    req.query('kind', mapped.kind);
    req.query('start_date', mapped.startDate);
    req.query('end_date', mapped.endDate);
    req.query('time_zone', mapped.timeZone);
    req.appendTemplatePath`/api/1/energy_sites/${mapped.energySiteId}/telemetry_history`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(chargeHistoryResponseSchema, requestOptions);
  }

  /**
   * @param energySiteId
   * @return Response from the API call
   */
  async getLiveSiteStatus(
    energySiteId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LiveStatusResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ energySiteId: [energySiteId, string()] });
    req.appendTemplatePath`/api/1/energy_sites/${mapped.energySiteId}/live_status`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(liveStatusResponseSchema, requestOptions);
  }

  /**
   * @param energySiteId
   * @param body
   * @return Response from the API call
   */
  async setSiteModeAutonomousOrSelfConsumption(
    energySiteId: string,
    body: OperationRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GenericUpdateResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      energySiteId: [energySiteId, string()],
      body: [body, operationRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/energy_sites/${mapped.energySiteId}/operation`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(genericUpdateResponseSchema, requestOptions);
  }

  /**
   * @param energySiteId
   * @param body
   * @return Response from the API call
   */
  async allowDisallowChargingFromTheGridAndExportingEnergyToTheGrid(
    energySiteId: string,
    body?: unknown,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GenericUpdateResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      energySiteId: [energySiteId, string()],
      body: [body, optional(unknown())],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/energy_sites/${mapped.energySiteId}/grid_import_export`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(genericUpdateResponseSchema, requestOptions);
  }

  /**
   * @param energySiteId
   * @param body
   * @return Response from the API call
   */
  async adjustSiteSOffGridVehicleChargingReserve(
    energySiteId: string,
    body: OffGridVehicleChargingReserveRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GenericUpdateResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      energySiteId: [energySiteId, string()],
      body: [body, offGridVehicleChargingReserveRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/energy_sites/${mapped.energySiteId}/off_grid_vehicle_charging_reserve`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(genericUpdateResponseSchema, requestOptions);
  }

  /**
   * @param energySiteId
   * @param body
   * @return Response from the API call
   */
  async updateStormWatchParticipation(
    energySiteId: string,
    body: StormModeRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GenericUpdateResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      energySiteId: [energySiteId, string()],
      body: [body, stormModeRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/energy_sites/${mapped.energySiteId}/storm_mode`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(genericUpdateResponseSchema, requestOptions);
  }

  /**
   * @param energySiteId
   * @param body
   * @return Response from the API call
   */
  async updateTimeOfUseTouSettings(
    energySiteId: string,
    body: TimeOfUseSettingsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GenericUpdateResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      energySiteId: [energySiteId, string()],
      body: [body, timeOfUseSettingsRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/energy_sites/${mapped.energySiteId}/time_of_use_settings`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(genericUpdateResponseSchema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getUserProductsVehiclesEnergySites(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProductsResponse>> {
    const req = this.createRequest('GET', '/api/1/products');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(productsResponseSchema, requestOptions);
  }

  /**
   * @param energySiteId
   * @return Response from the API call
   */
  async getSiteInformationAssetsSettingsFeatures(
    energySiteId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SiteInfoResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ energySiteId: [energySiteId, string()] });
    req.appendTemplatePath`/api/1/energy_sites/${mapped.energySiteId}/site_info`;
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(siteInfoResponseSchema, requestOptions);
  }
}
