/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  BackupResponse,
  backupResponseSchema,
} from '../models/backupResponse.js';
import {
  FleetTelemetryErrorsResponse,
  fleetTelemetryErrorsResponseSchema,
} from '../models/fleetTelemetryErrorsResponse.js';
import {
  PublicKeyResponse,
  publicKeyResponseSchema,
} from '../models/publicKeyResponse.js';
import {
  RegisterPartnerRequest,
  registerPartnerRequestSchema,
} from '../models/registerPartnerRequest.js';
import {
  RegisterPartnerResponse,
  registerPartnerResponseSchema,
} from '../models/registerPartnerResponse.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';

export class PartnerController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getVinsWithFleetTelemetryErrors(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BackupResponse>> {
    const req = this.createRequest(
      'GET',
      '/api/1/partner_accounts/fleet_telemetry_error_vins'
    );
    req.authenticate([{ bearerAuth: true, oauth2: true }]);
    return req.callAsJson(backupResponseSchema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getRecentFleetTelemetryErrors(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FleetTelemetryErrorsResponse>> {
    const req = this.createRequest(
      'GET',
      '/api/1/partner_accounts/fleet_telemetry_errors'
    );
    req.authenticate([{ bearerAuth: true, oauth2: true }]);
    return req.callAsJson(fleetTelemetryErrorsResponseSchema, requestOptions);
  }

  /**
   * @param domain
   * @return Response from the API call
   */
  async getPublicKeyForADomain(
    domain: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PublicKeyResponse>> {
    const req = this.createRequest('GET', '/api/1/partner_accounts/public_key');
    const mapped = req.prepareArgs({ domain: [domain, string()] });
    req.query('domain', mapped.domain);
    req.authenticate([{ bearerAuth: true, oauth2: true }]);
    return req.callAsJson(publicKeyResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async registerAPartnerAccount(
    body: RegisterPartnerRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RegisterPartnerResponse>> {
    const req = this.createRequest('POST', '/api/1/partner_accounts');
    const mapped = req.prepareArgs({
      body: [body, registerPartnerRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([{ bearerAuth: true, oauth2: true }]);
    return req.callAsJson(registerPartnerResponseSchema, requestOptions);
  }
}
