/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  BackupResponse,
  backupResponseSchema,
} from '../models/backupResponse.js';
import { MeResponse, meResponseSchema } from '../models/meResponse.js';
import {
  OrdersResponse,
  ordersResponseSchema,
} from '../models/ordersResponse.js';
import {
  RegionResponse,
  regionResponseSchema,
} from '../models/regionResponse.js';
import { BaseController } from './baseController.js';

export class UserController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getCustomFeatureFlagsForAUser(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BackupResponse>> {
    const req = this.createRequest('GET', '/api/1/users/feature_config');
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(backupResponseSchema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getSummaryOfAUserSAccount(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<MeResponse>> {
    const req = this.createRequest('GET', '/api/1/users/me');
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(meResponseSchema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getActiveOrdersForAUser(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<OrdersResponse>> {
    const req = this.createRequest('GET', '/api/1/users/orders');
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(ordersResponseSchema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getUserSRegionAndFleetApiBaseUrl(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RegionResponse>> {
    const req = this.createRequest('GET', '/api/1/users/region');
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(regionResponseSchema, requestOptions);
  }
}
