/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ActuateTrunkRequest,
  actuateTrunkRequestSchema,
} from '../models/actuateTrunkRequest.js';
import {
  AddChargeScheduleRequest,
  addChargeScheduleRequestSchema,
} from '../models/addChargeScheduleRequest.js';
import {
  AddPreconditionScheduleRequest,
  addPreconditionScheduleRequestSchema,
} from '../models/addPreconditionScheduleRequest.js';
import {
  AdjustVolumeRequest,
  adjustVolumeRequestSchema,
} from '../models/adjustVolumeRequest.js';
import {
  CommandResponse,
  commandResponseSchema,
} from '../models/commandResponse.js';
import {
  GuestModeRequest,
  guestModeRequestSchema,
} from '../models/guestModeRequest.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';

export class VehicleCommandsController extends BaseController {
  /**
   * Controls the front or rear trunk
   *
   * @param vehicleTag
   * @param body
   * @return Response from the API call
   */
  async actuateTrunk(
    vehicleTag: string,
    body: ActuateTrunkRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      vehicleTag: [vehicleTag, string()],
      body: [body, actuateTrunkRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/actuate_trunk`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @param body
   * @return Response from the API call
   */
  async addChargeSchedule(
    vehicleTag: string,
    body: AddChargeScheduleRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      vehicleTag: [vehicleTag, string()],
      body: [body, addChargeScheduleRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/add_charge_schedule`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @param body
   * @return Response from the API call
   */
  async addPreconditionSchedule(
    vehicleTag: string,
    body: AddPreconditionScheduleRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      vehicleTag: [vehicleTag, string()],
      body: [body, addPreconditionScheduleRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/add_precondition_schedule`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @param body
   * @return Response from the API call
   */
  async adjustMediaVolume(
    vehicleTag: string,
    body: AdjustVolumeRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      vehicleTag: [vehicleTag, string()],
      body: [body, adjustVolumeRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/adjust_volume`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async startClimatePreconditioning(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/auto_conditioning_start`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async stopClimatePreconditioning(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/auto_conditioning_stop`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async cancelSoftwareUpdate(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/cancel_software_update`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async chargeMaxRange(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/charge_max_range`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async openChargePortDoor(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/charge_port_door_open`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async closeChargePortDoor(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/charge_port_door_close`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async chargeStandard(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/charge_standard`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async startCharging(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/charge_start`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async stopCharging(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/charge_stop`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * Deactivates PIN to Drive and resets the associated PIN for supported firmware versions.
   *
   * @param vehicleTag
   * @return Response from the API call
   */
  async clearPinToDriveAdmin(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/clear_pin_to_drive_admin`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async lockDoors(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/door_lock`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async unlockDoors(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/door_unlock`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * Erases user data from the vehicle UI. Requires Guest Mode.
   *
   * @param vehicleTag
   * @return Response from the API call
   */
  async eraseUserData(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/erase_user_data`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * Briefly flashes vehicle headlights.
   *
   * @param vehicleTag
   * @return Response from the API call
   */
  async flashLights(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/flash_lights`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @param body
   * @return Response from the API call
   */
  async enableOrDisableGuestMode(
    vehicleTag: string,
    body: GuestModeRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      vehicleTag: [vehicleTag, string()],
      body: [body, guestModeRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/guest_mode`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async honkHorn(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/honk_horn`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async nextFavoriteMediaTrack(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CommandResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/command/media_next_fav`;
    req.authenticate([{ thirdpartytoken: true }]);
    return req.callAsJson(commandResponseSchema, requestOptions);
  }
}
