/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  Api1DxVehiclesOptionsResponse,
  api1DxVehiclesOptionsResponseSchema,
} from '../models/api1DxVehiclesOptionsResponse.js';
import {
  Api1DxWarrantyDetailsResponse,
  api1DxWarrantyDetailsResponseSchema,
} from '../models/api1DxWarrantyDetailsResponse.js';
import {
  Api1VehiclesMobileEnabledResponse,
  api1VehiclesMobileEnabledResponseSchema,
} from '../models/api1VehiclesMobileEnabledResponse.js';
import {
  Api1VehiclesNearbyChargingSitesResponse,
  api1VehiclesNearbyChargingSitesResponseSchema,
} from '../models/api1VehiclesNearbyChargingSitesResponse.js';
import {
  Api1VehiclesResponse,
  api1VehiclesResponseSchema,
} from '../models/api1VehiclesResponse.js';
import {
  Api1VehiclesResponseGetVehicle,
  api1VehiclesResponseGetVehicleSchema,
} from '../models/api1VehiclesResponseGetVehicle.js';
import {
  Api1VehiclesWakeUpResponse,
  api1VehiclesWakeUpResponseSchema,
} from '../models/api1VehiclesWakeUpResponse.js';
import {
  DriversResponse,
  driversResponseSchema,
} from '../models/driversResponse.js';
import {
  EnterprisePayerRequest,
  enterprisePayerRequestSchema,
} from '../models/enterprisePayerRequest.js';
import {
  FleetStatusRequest,
  fleetStatusRequestSchema,
} from '../models/fleetStatusRequest.js';
import {
  FleetTelemetryJwsRequest,
  fleetTelemetryJwsRequestSchema,
} from '../models/fleetTelemetryJwsRequest.js';
import {
  SimpleOkResponse,
  simpleOkResponseSchema,
} from '../models/simpleOkResponse.js';
import {
  SiteInfoResponse,
  siteInfoResponseSchema,
} from '../models/siteInfoResponse.js';
import { optional, string, unknown } from '../schema.js';
import { BaseController } from './baseController.js';

export class VehiclesController extends BaseController {
  /**
   * @return Response from the API call
   */
  async listVehicles(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Api1VehiclesResponse>> {
    const req = this.createRequest('GET', '/api/1/vehicles');
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(api1VehiclesResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async getVehicle(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Api1VehiclesResponseGetVehicle>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(api1VehiclesResponseGetVehicleSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async mobileEnabled(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Api1VehiclesMobileEnabledResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/mobile_enabled`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(
      api1VehiclesMobileEnabledResponseSchema,
      requestOptions
    );
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async nearbyChargingSites(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Api1VehiclesNearbyChargingSitesResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/nearby_charging_sites`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(
      api1VehiclesNearbyChargingSitesResponseSchema,
      requestOptions
    );
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async vehicleLiveData(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SiteInfoResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/vehicle_data`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(siteInfoResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async wakeUpVehicle(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Api1VehiclesWakeUpResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/wake_up`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(api1VehiclesWakeUpResponseSchema, requestOptions);
  }

  /**
   * @param vin
   * @return Response from the API call
   */
  async vehicleSpecs(
    vin: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SiteInfoResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ vin: [vin, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vin}/specs`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(siteInfoResponseSchema, requestOptions);
  }

  /**
   * @param vin
   * @return Response from the API call
   */
  async vehicleOptions(
    vin: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Api1DxVehiclesOptionsResponse>> {
    const req = this.createRequest('GET', '/api/1/dx/vehicles/options');
    const mapped = req.prepareArgs({ vin: [vin, string()] });
    req.query('vin', mapped.vin);
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(api1DxVehiclesOptionsResponseSchema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async warrantyDetails(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Api1DxWarrantyDetailsResponse>> {
    const req = this.createRequest('GET', '/api/1/dx/warranty/details');
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(api1DxWarrantyDetailsResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async getAllowedDriversForAVehicle(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DriversResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/drivers`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(driversResponseSchema, requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async removeDriverAccessFromAVehicle(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SimpleOkResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/drivers`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(simpleOkResponseSchema, requestOptions);
  }

  /**
   * @param vin
   * @return Response from the API call
   */
  async getEligibleVehicleSubscriptions(
    vin: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SiteInfoResponse>> {
    const req = this.createRequest(
      'GET',
      '/api/1/dx/vehicles/subscriptions/eligibility'
    );
    const mapped = req.prepareArgs({ vin: [vin, string()] });
    req.query('vin', mapped.vin);
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(siteInfoResponseSchema, requestOptions);
  }

  /**
   * @param vin
   * @return Response from the API call
   */
  async getEligibleVehicleUpgrades(
    vin: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SiteInfoResponse>> {
    const req = this.createRequest(
      'GET',
      '/api/1/dx/vehicles/upgrades/eligibility'
    );
    const mapped = req.prepareArgs({ vin: [vin, string()] });
    req.query('vin', mapped.vin);
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(siteInfoResponseSchema, requestOptions);
  }

  /**
   * @param vin
   * @param body
   * @return Response from the API call
   */
  async setEnterprisePayerRoles(
    vin: string,
    body: EnterprisePayerRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      vin: [vin, string()],
      body: [body, enterprisePayerRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/1/dx/enterprise/v1/${mapped.vin}/payer`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.call(requestOptions);
  }

  /**
   * @param vin
   * @return Response from the API call
   */
  async getEnterpriseRolesForAVehicle(
    vin: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ vin: [vin, string()] });
    req.appendTemplatePath`/api/1/dx/enterprise/v1/${mapped.vin}/roles`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async getFleetStatusForVehicles(
    body: FleetStatusRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('POST', '/api/1/vehicles/fleet_status');
    const mapped = req.prepareArgs({ body: [body, fleetStatusRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async createOrUpdateFleetTelemetryConfiguration(
    body: unknown,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest(
      'POST',
      '/api/1/vehicles/fleet_telemetry_config'
    );
    const mapped = req.prepareArgs({ body: [body, optional(unknown())] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async getFleetTelemetryConfiguration(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/fleet_telemetry_config`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async deleteFleetTelemetryConfiguration(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/fleet_telemetry_config`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async configureFleetTelemetryUsingSignedJwsToken(
    body: FleetTelemetryJwsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest(
      'POST',
      '/api/1/vehicles/fleet_telemetry_config_jws'
    );
    const mapped = req.prepareArgs({
      body: [body, fleetTelemetryJwsRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }

  /**
   * @param vehicleTag
   * @return Response from the API call
   */
  async getFleetTelemetryErrorsForAVehicle(
    vehicleTag: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ vehicleTag: [vehicleTag, string()] });
    req.appendTemplatePath`/api/1/vehicles/${mapped.vehicleTag}/fleet_telemetry_errors`;
    req.authenticate([{ thirdpartytoken: true }, { bearerAuth: true }]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }
}
