/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';
import { WhichTrunk, whichTrunkSchema } from './whichTrunk.js';

export interface ActuateTrunkRequest {
  whichTrunk: WhichTrunk;
  additionalProperties?: Record<string, unknown>;
}

export const actuateTrunkRequestSchema: Schema<ActuateTrunkRequest> = typedExpandoObject(
  { whichTrunk: ['which_trunk', whichTrunkSchema] },
  'additionalProperties',
  optional(unknown())
);
