/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AddChargeScheduleRequest {
  lat: number;
  lon: number;
  id: number;
  daysOfWeek?: string;
  startEnabled?: boolean;
  startTime?: number;
  endEnabled?: boolean;
  endTime?: number;
  oneTime?: boolean;
  enabled: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const addChargeScheduleRequestSchema: Schema<AddChargeScheduleRequest> = typedExpandoObject(
  {
    lat: ['lat', number()],
    lon: ['lon', number()],
    id: ['id', number()],
    daysOfWeek: ['days_of_week', optional(string())],
    startEnabled: ['start_enabled', optional(boolean())],
    startTime: ['start_time', optional(number())],
    endEnabled: ['end_enabled', optional(boolean())],
    endTime: ['end_time', optional(number())],
    oneTime: ['one_time', optional(boolean())],
    enabled: ['enabled', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
