/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AddPreconditionScheduleRequest {
  lat: number;
  lon: number;
  id: number;
  daysOfWeek?: string;
  preconditionTime?: number;
  oneTime?: boolean;
  enabled: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const addPreconditionScheduleRequestSchema: Schema<AddPreconditionScheduleRequest> = typedExpandoObject(
  {
    lat: ['lat', number()],
    lon: ['lon', number()],
    id: ['id', number()],
    daysOfWeek: ['days_of_week', optional(string())],
    preconditionTime: ['precondition_time', optional(number())],
    oneTime: ['one_time', optional(boolean())],
    enabled: ['enabled', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
