/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AdjustVolumeRequest {
  volume: number;
  additionalProperties?: Record<string, unknown>;
}

export const adjustVolumeRequestSchema: Schema<AdjustVolumeRequest> = typedExpandoObject(
  { volume: ['volume', number()] },
  'additionalProperties',
  optional(unknown())
);
