/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Pagination, paginationSchema } from './pagination.js';
import { VehicleBase, vehicleBaseSchema } from './vehicleBase.js';

export interface Api1VehiclesResponse {
  response?: VehicleBase[];
  pagination?: Pagination;
  count?: number;
  additionalProperties?: Record<string, unknown>;
}

export const api1VehiclesResponseSchema: Schema<Api1VehiclesResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        response: ['response', optional(array(vehicleBaseSchema))],
        pagination: ['pagination', optional(paginationSchema)],
        count: ['count', optional(number())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
