/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseApi1DxVehiclesOptionsResponse,
  responseApi1DxVehiclesOptionsResponseSchema,
} from './responseApi1DxVehiclesOptionsResponse.js';

export interface Api1DxVehiclesOptionsResponse {
  response?: ResponseApi1DxVehiclesOptionsResponse;
  additionalProperties?: Record<string, unknown>;
}

export const api1DxVehiclesOptionsResponseSchema: Schema<Api1DxVehiclesOptionsResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        response: [
          'response',
          optional(responseApi1DxVehiclesOptionsResponseSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
