/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseApi1DxWarrantyDetailsResponse,
  responseApi1DxWarrantyDetailsResponseSchema,
} from './responseApi1DxWarrantyDetailsResponse.js';

export interface Api1DxWarrantyDetailsResponse {
  response?: ResponseApi1DxWarrantyDetailsResponse;
  additionalProperties?: Record<string, unknown>;
}

export const api1DxWarrantyDetailsResponseSchema: Schema<Api1DxWarrantyDetailsResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        response: [
          'response',
          optional(responseApi1DxWarrantyDetailsResponseSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
