/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { VehicleBase, vehicleBaseSchema } from './vehicleBase.js';

export interface Api1VehiclesResponseGetVehicle {
  response?: VehicleBase;
  additionalProperties?: Record<string, unknown>;
}

export const api1VehiclesResponseGetVehicleSchema: Schema<Api1VehiclesResponseGetVehicle> = lazy(
  () =>
    typedExpandoObject(
      { response: ['response', optional(vehicleBaseSchema)] },
      'additionalProperties',
      optional(unknown())
    )
);
