/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MobileEnabled, mobileEnabledSchema } from './mobileEnabled.js';

export interface Api1VehiclesMobileEnabledResponse {
  response?: MobileEnabled;
  additionalProperties?: Record<string, unknown>;
}

export const api1VehiclesMobileEnabledResponseSchema: Schema<Api1VehiclesMobileEnabledResponse> = lazy(
  () =>
    typedExpandoObject(
      { response: ['response', optional(mobileEnabledSchema)] },
      'additionalProperties',
      optional(unknown())
    )
);
