/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Response3, response3Schema } from './response3.js';

export interface Api1VehiclesNearbyChargingSitesResponse {
  response?: Response3;
  additionalProperties?: Record<string, unknown>;
}

export const api1VehiclesNearbyChargingSitesResponseSchema: Schema<Api1VehiclesNearbyChargingSitesResponse> = lazy(
  () =>
    typedExpandoObject(
      { response: ['response', optional(response3Schema)] },
      'additionalProperties',
      optional(unknown())
    )
);
