/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BackupRequest {
  backupReservePercent: number;
  additionalProperties?: Record<string, unknown>;
}

export const backupRequestSchema: Schema<BackupRequest> = typedExpandoObject(
  { backupReservePercent: ['backup_reserve_percent', number()] },
  'additionalProperties',
  optional(unknown())
);
