/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseCalendarHistoryResponse,
  responseCalendarHistoryResponseSchema,
} from './responseCalendarHistoryResponse.js';

export interface CalendarHistoryResponse {
  response: ResponseCalendarHistoryResponse;
  additionalProperties?: Record<string, unknown>;
}

export const calendarHistoryResponseSchema: Schema<CalendarHistoryResponse> = lazy(
  () =>
    typedExpandoObject(
      { response: ['response', responseCalendarHistoryResponseSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
