/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ChargeStartTime {
  seconds: number;
  additionalProperties?: Record<string, unknown>;
}

export const chargeStartTimeSchema: Schema<ChargeStartTime> = typedExpandoObject(
  { seconds: ['seconds', number()] },
  'additionalProperties',
  optional(unknown())
);
