/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ChargingSessionsData,
  chargingSessionsDataSchema,
} from './chargingSessionsData.js';

export interface ChargingSessionsResponse {
  response: ChargingSessionsData;
  additionalProperties?: Record<string, unknown>;
}

export const chargingSessionsResponseSchema: Schema<ChargingSessionsResponse> = lazy(
  () =>
    typedExpandoObject(
      { response: ['response', chargingSessionsDataSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
