/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ChargingPeriod, chargingPeriodSchema } from './chargingPeriod.js';
import { Location, locationSchema } from './location.js';
import { Tariffs, tariffsSchema } from './tariffs.js';
import { TotalCost, totalCostSchema } from './totalCost.js';

export interface ChargingSession {
  id?: string;
  vin?: string;
  model?: string;
  startDateTime?: string;
  stopDateTime?: string;
  totalEnergy?: number;
  totalTime?: number;
  totalCost?: TotalCost;
  location?: Location;
  chargingPeriods?: ChargingPeriod[];
  tariffs?: Tariffs;
  additionalProperties?: Record<string, unknown>;
}

export const chargingSessionSchema: Schema<ChargingSession> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', optional(string())],
      vin: ['vin', optional(string())],
      model: ['model', optional(string())],
      startDateTime: ['start_date_time', optional(string())],
      stopDateTime: ['stop_date_time', optional(string())],
      totalEnergy: ['total_energy', optional(number())],
      totalTime: ['total_time', optional(number())],
      totalCost: ['total_cost', optional(totalCostSchema)],
      location: ['location', optional(locationSchema)],
      chargingPeriods: [
        'charging_periods',
        optional(array(chargingPeriodSchema)),
      ],
      tariffs: ['tariffs', optional(tariffsSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
