/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ChargingHistoryItem,
  chargingHistoryItemSchema,
} from './chargingHistoryItem.js';

export interface ChargingHistoryData {
  data: ChargingHistoryItem[];
  additionalProperties?: Record<string, unknown>;
}

export const chargingHistoryDataSchema: Schema<ChargingHistoryData> = lazy(() =>
  typedExpandoObject(
    { data: ['data', array(chargingHistoryItemSchema)] },
    'additionalProperties',
    optional(unknown())
  )
);
