/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseChargeHistoryResponse,
  responseChargeHistoryResponseSchema,
} from './responseChargeHistoryResponse.js';

export interface ChargeHistoryResponse {
  response: ResponseChargeHistoryResponse;
  additionalProperties?: Record<string, unknown>;
}

export const chargeHistoryResponseSchema: Schema<ChargeHistoryResponse> = lazy(
  () =>
    typedExpandoObject(
      { response: ['response', responseChargeHistoryResponseSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
