/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ChargingDimension,
  chargingDimensionSchema,
} from './chargingDimension.js';

export interface ChargingPeriod {
  startDateTime?: string;
  dimensions?: ChargingDimension[];
  additionalProperties?: Record<string, unknown>;
}

export const chargingPeriodSchema: Schema<ChargingPeriod> = lazy(() =>
  typedExpandoObject(
    {
      startDateTime: ['start_date_time', optional(string())],
      dimensions: ['dimensions', optional(array(chargingDimensionSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
