/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Location1, location1Schema } from './location1.js';

export interface ChargingLocation {
  name?: string;
  type?: string;
  distanceMiles?: number;
  amenities?: string;
  availableStalls?: number;
  totalStalls?: number;
  siteClosed?: boolean;
  billingInfo?: string;
  location?: Location1;
  additionalProperties?: Record<string, unknown>;
}

export const chargingLocationSchema: Schema<ChargingLocation> = lazy(() =>
  typedExpandoObject(
    {
      name: ['name', optional(string())],
      type: ['type', optional(string())],
      distanceMiles: ['distance_miles', optional(number())],
      amenities: ['amenities', optional(string())],
      availableStalls: ['available_stalls', optional(number())],
      totalStalls: ['total_stalls', optional(number())],
      siteClosed: ['site_closed', optional(boolean())],
      billingInfo: ['billing_info', optional(string())],
      location: ['location', optional(location1Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
