/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ChargingFee, chargingFeeSchema } from './chargingFee.js';
import { ChargingInvoice, chargingInvoiceSchema } from './chargingInvoice.js';

export interface ChargingHistoryItem {
  sessionId: number;
  vin: string;
  siteLocationName?: string;
  chargeStartDateTime?: string;
  chargeStopDateTime?: string;
  unlatchDateTime?: string;
  countryCode?: string;
  fees?: ChargingFee[];
  billingType?: string;
  invoices?: ChargingInvoice[];
  vehicleMakeType?: string;
  additionalProperties?: Record<string, unknown>;
}

export const chargingHistoryItemSchema: Schema<ChargingHistoryItem> = lazy(() =>
  typedExpandoObject(
    {
      sessionId: ['sessionId', number()],
      vin: ['vin', string()],
      siteLocationName: ['siteLocationName', optional(string())],
      chargeStartDateTime: ['chargeStartDateTime', optional(string())],
      chargeStopDateTime: ['chargeStopDateTime', optional(string())],
      unlatchDateTime: ['unlatchDateTime', optional(string())],
      countryCode: ['countryCode', optional(string())],
      fees: ['fees', optional(array(chargingFeeSchema))],
      billingType: ['billingType', optional(string())],
      invoices: ['invoices', optional(array(chargingInvoiceSchema))],
      vehicleMakeType: ['vehicleMakeType', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
