/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ChargingSession, chargingSessionSchema } from './chargingSession.js';

export interface ChargingSessionsData {
  data?: ChargingSession[];
  statusCode?: number;
  statusMessage?: string;
  timestamp?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const chargingSessionsDataSchema: Schema<ChargingSessionsData> = lazy(
  () =>
    typedExpandoObject(
      {
        data: ['data', optional(array(chargingSessionSchema))],
        statusCode: ['status_code', optional(number())],
        statusMessage: ['status_message', optional(string())],
        timestamp: ['timestamp', optional(dict(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
