/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ChargingHistoryData,
  chargingHistoryDataSchema,
} from './chargingHistoryData.js';

export interface ChargingHistoryResponse {
  response: ChargingHistoryData;
  additionalProperties?: Record<string, unknown>;
}

export const chargingHistoryResponseSchema: Schema<ChargingHistoryResponse> = lazy(
  () =>
    typedExpandoObject(
      { response: ['response', chargingHistoryDataSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
