/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ChargeDuration, chargeDurationSchema } from './chargeDuration.js';
import { ChargeStartTime, chargeStartTimeSchema } from './chargeStartTime.js';

export interface ChargeHistory {
  chargeStartTime: ChargeStartTime;
  chargeDuration: ChargeDuration;
  energyAddedWh: number;
  additionalProperties?: Record<string, unknown>;
}

export const chargeHistorySchema: Schema<ChargeHistory> = lazy(() =>
  typedExpandoObject(
    {
      chargeStartTime: ['charge_start_time', chargeStartTimeSchema],
      chargeDuration: ['charge_duration', chargeDurationSchema],
      energyAddedWh: ['energy_added_wh', number()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
