/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ChargingInvoice {
  fileName?: string;
  contentId?: string;
  invoiceType?: string;
  additionalProperties?: Record<string, unknown>;
}

export const chargingInvoiceSchema: Schema<ChargingInvoice> = typedExpandoObject(
  {
    fileName: ['fileName', optional(string())],
    contentId: ['contentId', optional(string())],
    invoiceType: ['invoiceType', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
