/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ChargingFee {
  sessionFeeId?: number;
  feeType?: string;
  currencyCode?: string;
  pricingType?: string;
  rateBase?: number;
  rateTier1?: number;
  rateTier2?: number;
  rateTier3?: number | null;
  rateTier4?: number | null;
  usageBase?: number;
  usageTier1?: number;
  usageTier2?: number;
  usageTier3?: number | null;
  usageTier4?: number | null;
  totalBase?: number;
  totalTier1?: number;
  totalTier2?: number;
  totalTier3?: number;
  totalTier4?: number;
  totalDue?: number;
  netDue?: number;
  uom?: string;
  isPaid?: boolean;
  status?: string;
  additionalProperties?: Record<string, unknown>;
}

export const chargingFeeSchema: Schema<ChargingFee> = typedExpandoObject(
  {
    sessionFeeId: ['sessionFeeId', optional(number())],
    feeType: ['feeType', optional(string())],
    currencyCode: ['currencyCode', optional(string())],
    pricingType: ['pricingType', optional(string())],
    rateBase: ['rateBase', optional(number())],
    rateTier1: ['rateTier1', optional(number())],
    rateTier2: ['rateTier2', optional(number())],
    rateTier3: ['rateTier3', optional(nullable(number()))],
    rateTier4: ['rateTier4', optional(nullable(number()))],
    usageBase: ['usageBase', optional(number())],
    usageTier1: ['usageTier1', optional(number())],
    usageTier2: ['usageTier2', optional(number())],
    usageTier3: ['usageTier3', optional(nullable(number()))],
    usageTier4: ['usageTier4', optional(nullable(number()))],
    totalBase: ['totalBase', optional(number())],
    totalTier1: ['totalTier1', optional(number())],
    totalTier2: ['totalTier2', optional(number())],
    totalTier3: ['totalTier3', optional(number())],
    totalTier4: ['totalTier4', optional(number())],
    totalDue: ['totalDue', optional(number())],
    netDue: ['netDue', optional(number())],
    uom: ['uom', optional(string())],
    isPaid: ['isPaid', optional(boolean())],
    status: ['status', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
