/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CommandResult, commandResultSchema } from './commandResult.js';

export interface CommandResponse {
  response?: CommandResult;
  additionalProperties?: Record<string, unknown>;
}

export const commandResponseSchema: Schema<CommandResponse> = lazy(() =>
  typedExpandoObject(
    { response: ['response', optional(commandResultSchema)] },
    'additionalProperties',
    optional(unknown())
  )
);
