/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CommandResult {
  result: boolean;
  reason: string;
  additionalProperties?: Record<string, unknown>;
}

export const commandResultSchema: Schema<CommandResult> = typedExpandoObject(
  { result: ['result', boolean()], reason: ['reason', string()] },
  'additionalProperties',
  optional(unknown())
);
