/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DefaultRealMode
 */
export enum DefaultRealMode {
  Autonomous = 'autonomous',
  SelfConsumption = 'self_consumption',
}

/**
 * Schema for DefaultRealMode
 */
export const defaultRealModeSchema: Schema<DefaultRealMode> = stringEnum(
  DefaultRealMode,
  true
);
