/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Driver, driverSchema } from './driver.js';

export interface DriversResponse {
  response?: Driver[];
  count?: number;
  additionalProperties?: Record<string, unknown>;
}

export const driversResponseSchema: Schema<DriversResponse> = lazy(() =>
  typedExpandoObject(
    {
      response: ['response', optional(array(driverSchema))],
      count: ['count', optional(number())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
