/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Driver {
  myTeslaUniqueId?: number;
  userId?: number;
  userIdS?: string;
  vaultUuid?: string;
  driverFirstName?: string;
  driverLastName?: string;
  granularAccess?: unknown;
  activePubkeys?: string[];
  publicKey?: string;
  additionalProperties?: Record<string, unknown>;
}

export const driverSchema: Schema<Driver> = typedExpandoObject(
  {
    myTeslaUniqueId: ['my_tesla_unique_id', optional(number())],
    userId: ['user_id', optional(number())],
    userIdS: ['user_id_s', optional(string())],
    vaultUuid: ['vault_uuid', optional(string())],
    driverFirstName: ['driver_first_name', optional(string())],
    driverLastName: ['driver_last_name', optional(string())],
    granularAccess: ['granular_access', optional(unknown())],
    activePubkeys: ['active_pubkeys', optional(array(string()))],
    publicKey: ['public_key', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
