/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EnterprisePayerRequest {
  role: string;
  federationId?: string;
  accountId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const enterprisePayerRequestSchema: Schema<EnterprisePayerRequest> = typedExpandoObject(
  {
    role: ['role', string()],
    federationId: ['federation_id', optional(string())],
    accountId: ['account_id', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
