/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FleetTelemetryError {
  name: string;
  error: string;
  vin: string;
  additionalProperties?: Record<string, unknown>;
}

export const fleetTelemetryErrorSchema: Schema<FleetTelemetryError> = typedExpandoObject(
  {
    name: ['name', string()],
    error: ['error', string()],
    vin: ['vin', string()],
  },
  'additionalProperties',
  optional(unknown())
);
