/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseFleetTelemetryErrorsResponse,
  responseFleetTelemetryErrorsResponseSchema,
} from './responseFleetTelemetryErrorsResponse.js';

export interface FleetTelemetryErrorsResponse {
  response: ResponseFleetTelemetryErrorsResponse;
  additionalProperties?: Record<string, unknown>;
}

export const fleetTelemetryErrorsResponseSchema: Schema<FleetTelemetryErrorsResponse> = lazy(
  () =>
    typedExpandoObject(
      { response: ['response', responseFleetTelemetryErrorsResponseSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
