/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FleetTelemetryJwsRequest {
  token?: string;
  vins?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const fleetTelemetryJwsRequestSchema: Schema<FleetTelemetryJwsRequest> = typedExpandoObject(
  {
    token: ['token', optional(string())],
    vins: ['vins', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
