/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FleetStatusRequest {
  vins?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const fleetStatusRequestSchema: Schema<FleetStatusRequest> = typedExpandoObject(
  { vins: ['vins', optional(array(string()))] },
  'additionalProperties',
  optional(unknown())
);
