/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Response, responseSchema } from './response.js';

export interface GenericUpdateResponse {
  response: Response;
  additionalProperties?: Record<string, unknown>;
}

export const genericUpdateResponseSchema: Schema<GenericUpdateResponse> = lazy(
  () =>
    typedExpandoObject(
      { response: ['response', responseSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
