/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface GuestModeRequest {
  /** Enable or disable Guest Mode */
  enable: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const guestModeRequestSchema: Schema<GuestModeRequest> = typedExpandoObject(
  { enable: ['enable', boolean()] },
  'additionalProperties',
  optional(unknown())
);
