/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Kind
 */
export enum Kind {
  Backup = 'backup',
  Energy = 'energy',
}

/**
 * Schema for Kind
 */
export const kindSchema: Schema<Kind> = stringEnum(Kind, true);
