/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for KindGetWallConnectorChargingHistory
 */
export enum KindGetWallConnectorChargingHistory {
  Charge = 'charge',
}

/**
 * Schema for KindGetWallConnectorChargingHistory
 */
export const kindGetWallConnectorChargingHistorySchema: Schema<KindGetWallConnectorChargingHistory> = stringEnum(
  KindGetWallConnectorChargingHistory,
  true
);
