/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseLiveStatusResponse,
  responseLiveStatusResponseSchema,
} from './responseLiveStatusResponse.js';

export interface LiveStatusResponse {
  response: ResponseLiveStatusResponse;
  additionalProperties?: Record<string, unknown>;
}

export const liveStatusResponseSchema: Schema<LiveStatusResponse> = lazy(() =>
  typedExpandoObject(
    { response: ['response', responseLiveStatusResponseSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
