/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Location {
  country?: string;
  name?: string;
  additionalProperties?: Record<string, unknown>;
}

export const locationSchema: Schema<Location> = typedExpandoObject(
  {
    country: ['country', optional(string())],
    name: ['name', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
