/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Location1 {
  lat?: number;
  mLong?: number;
  additionalProperties?: Record<string, unknown>;
}

export const location1Schema: Schema<Location1> = typedExpandoObject(
  { lat: ['lat', optional(number())], mLong: ['long', optional(number())] },
  'additionalProperties',
  optional(unknown())
);
