/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseMeResponse,
  responseMeResponseSchema,
} from './responseMeResponse.js';

export interface MeResponse {
  response: ResponseMeResponse;
  additionalProperties?: Record<string, unknown>;
}

export const meResponseSchema: Schema<MeResponse> = lazy(() =>
  typedExpandoObject(
    { response: ['response', responseMeResponseSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
