/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MobileEnabled {
  result?: boolean;
  reason?: string;
  additionalProperties?: Record<string, unknown>;
}

export const mobileEnabledSchema: Schema<MobileEnabled> = typedExpandoObject(
  {
    result: ['result', optional(boolean())],
    reason: ['reason', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
