/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OAuthScopeOauth2
 */
export enum OAuthScopeOauth2 {
  Openid = 'openid',
  OfflineAccess = 'offline_access',
  UserData = 'user_data',
  VehicleDeviceData = 'vehicle_device_data',
  VehicleLocation = 'vehicle_location',
  VehicleCmds = 'vehicle_cmds',
  VehicleChargingCmds = 'vehicle_charging_cmds',
  VehicleSpecs = 'vehicle_specs',
  EnergyDeviceData = 'energy_device_data',
  EnergyCmds = 'energy_cmds',
  EnterpriseManagement = 'enterprise_management',
}

/**
 * Schema for OAuthScopeOauth2
 */
export const oAuthScopeOauth2Schema: Schema<OAuthScopeOauth2> = stringEnum(
  OAuthScopeOauth2
);
