/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';
import { DefaultRealMode, defaultRealModeSchema } from './defaultRealMode.js';

export interface OperationRequest {
  defaultRealMode: DefaultRealMode;
  additionalProperties?: Record<string, unknown>;
}

export const operationRequestSchema: Schema<OperationRequest> = typedExpandoObject(
  { defaultRealMode: ['default_real_mode', defaultRealModeSchema] },
  'additionalProperties',
  optional(unknown())
);
