/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseOrdersResponse,
  responseOrdersResponseSchema,
} from './responseOrdersResponse.js';

export interface OrdersResponse {
  response: ResponseOrdersResponse[];
  count: number;
  additionalProperties?: Record<string, unknown>;
}

export const ordersResponseSchema: Schema<OrdersResponse> = lazy(() =>
  typedExpandoObject(
    {
      response: ['response', array(responseOrdersResponseSchema)],
      count: ['count', number()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
