/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Pagination {
  previous?: number | null;
  next?: number | null;
  current?: number;
  perPage?: number;
  count?: number;
  pages?: number;
  additionalProperties?: Record<string, unknown>;
}

export const paginationSchema: Schema<Pagination> = typedExpandoObject(
  {
    previous: ['previous', optional(nullable(number()))],
    next: ['next', optional(nullable(number()))],
    current: ['current', optional(number())],
    perPage: ['per_page', optional(number())],
    count: ['count', optional(number())],
    pages: ['pages', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
