/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PriceComponent {
  type?: string;
  price?: number;
  stepSize?: number;
  additionalProperties?: Record<string, unknown>;
}

export const priceComponentSchema: Schema<PriceComponent> = typedExpandoObject(
  {
    type: ['type', optional(string())],
    price: ['price', optional(number())],
    stepSize: ['step_size', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
