/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProductsResponse {
  response?: unknown[];
  count?: number;
  additionalProperties?: Record<string, unknown>;
}

export const productsResponseSchema: Schema<ProductsResponse> = typedExpandoObject(
  {
    response: ['response', optional(array(unknown()))],
    count: ['count', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
