/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseRegisterPartnerResponse,
  responseRegisterPartnerResponseSchema,
} from './responseRegisterPartnerResponse.js';

export interface RegisterPartnerResponse {
  response: ResponseRegisterPartnerResponse;
  additionalProperties?: Record<string, unknown>;
}

export const registerPartnerResponseSchema: Schema<RegisterPartnerResponse> = lazy(
  () =>
    typedExpandoObject(
      { response: ['response', responseRegisterPartnerResponseSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
