/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseRegionResponse,
  responseRegionResponseSchema,
} from './responseRegionResponse.js';

export interface RegionResponse {
  response: ResponseRegionResponse;
  additionalProperties?: Record<string, unknown>;
}

export const regionResponseSchema: Schema<RegionResponse> = lazy(() =>
  typedExpandoObject(
    { response: ['response', responseRegionResponseSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
