/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ResponseLiveStatusResponse {
  solarPower: number;
  energyLeft: number;
  totalPackEnergy: number;
  percentageCharged: number;
  backupCapable: boolean;
  batteryPower?: number;
  loadPower?: number;
  gridStatus?: string;
  gridPower?: number;
  islandStatus?: string;
  stormModeActive?: boolean;
  timestamp?: string;
  additionalProperties?: Record<string, unknown>;
}

export const responseLiveStatusResponseSchema: Schema<ResponseLiveStatusResponse> = typedExpandoObject(
  {
    solarPower: ['solar_power', number()],
    energyLeft: ['energy_left', number()],
    totalPackEnergy: ['total_pack_energy', number()],
    percentageCharged: ['percentage_charged', number()],
    backupCapable: ['backup_capable', boolean()],
    batteryPower: ['battery_power', optional(number())],
    loadPower: ['load_power', optional(number())],
    gridStatus: ['grid_status', optional(string())],
    gridPower: ['grid_power', optional(number())],
    islandStatus: ['island_status', optional(string())],
    stormModeActive: ['storm_mode_active', optional(boolean())],
    timestamp: ['timestamp', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
