/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ResponsePublicKeyResponse {
  publicKey: string;
  additionalProperties?: Record<string, unknown>;
}

export const responsePublicKeyResponseSchema: Schema<ResponsePublicKeyResponse> = typedExpandoObject(
  { publicKey: ['public_key', string()] },
  'additionalProperties',
  optional(unknown())
);
