/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { WarrantyItem, warrantyItemSchema } from './warrantyItem.js';

export interface ResponseApi1DxWarrantyDetailsResponse {
  activeWarranty?: WarrantyItem[];
  upcomingWarranty?: WarrantyItem[];
  expiredWarranty?: WarrantyItem[];
  additionalProperties?: Record<string, unknown>;
}

export const responseApi1DxWarrantyDetailsResponseSchema: Schema<ResponseApi1DxWarrantyDetailsResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        activeWarranty: ['activeWarranty', optional(array(warrantyItemSchema))],
        upcomingWarranty: [
          'upcomingWarranty',
          optional(array(warrantyItemSchema)),
        ],
        expiredWarranty: [
          'expiredWarranty',
          optional(array(warrantyItemSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
