/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ChargeHistory, chargeHistorySchema } from './chargeHistory.js';

export interface ResponseChargeHistoryResponse {
  chargeHistory: ChargeHistory[];
  additionalProperties?: Record<string, unknown>;
}

export const responseChargeHistoryResponseSchema: Schema<ResponseChargeHistoryResponse> = lazy(
  () =>
    typedExpandoObject(
      { chargeHistory: ['charge_history', array(chargeHistorySchema)] },
      'additionalProperties',
      optional(unknown())
    )
);
