/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ResponseMeResponse {
  email: string;
  fullName: string;
  profileImageUrl: string;
  vaultUuid: string;
  additionalProperties?: Record<string, unknown>;
}

export const responseMeResponseSchema: Schema<ResponseMeResponse> = typedExpandoObject(
  {
    email: ['email', string()],
    fullName: ['full_name', string()],
    profileImageUrl: ['profile_image_url', string()],
    vaultUuid: ['vault_uuid', string()],
  },
  'additionalProperties',
  optional(unknown())
);
