/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { VehicleOption, vehicleOptionSchema } from './vehicleOption.js';

export interface ResponseApi1DxVehiclesOptionsResponse {
  codes?: VehicleOption[];
  additionalProperties?: Record<string, unknown>;
}

export const responseApi1DxVehiclesOptionsResponseSchema: Schema<ResponseApi1DxVehiclesOptionsResponse> = lazy(
  () =>
    typedExpandoObject(
      { codes: ['codes', optional(array(vehicleOptionSchema))] },
      'additionalProperties',
      optional(unknown())
    )
);
