/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Response {
  code: number;
  message: string;
  additionalProperties?: Record<string, unknown>;
}

export const responseSchema: Schema<Response> = typedExpandoObject(
  { code: ['code', number()], message: ['message', string()] },
  'additionalProperties',
  optional(unknown())
);
