/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ResponseRegionResponse {
  region: string;
  fleetApiBaseUrl: string;
  additionalProperties?: Record<string, unknown>;
}

export const responseRegionResponseSchema: Schema<ResponseRegionResponse> = typedExpandoObject(
  {
    region: ['region', string()],
    fleetApiBaseUrl: ['fleet_api_base_url', string()],
  },
  'additionalProperties',
  optional(unknown())
);
