/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ResponseOrdersResponse {
  vehicleMapId: number;
  referenceNumber: string;
  vin: string;
  orderStatus: string;
  orderSubstatus: string;
  modelCode: string;
  countryCode: string;
  locale: string;
  mktOptions: string;
  isB2B: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const responseOrdersResponseSchema: Schema<ResponseOrdersResponse> = typedExpandoObject(
  {
    vehicleMapId: ['vehicleMapId', number()],
    referenceNumber: ['referenceNumber', string()],
    vin: ['vin', string()],
    orderStatus: ['orderStatus', string()],
    orderSubstatus: ['orderSubstatus', string()],
    modelCode: ['modelCode', string()],
    countryCode: ['countryCode', string()],
    locale: ['locale', string()],
    mktOptions: ['mktOptions', string()],
    isB2B: ['isB2b', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
