/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Signaling, signalingSchema } from './signaling.js';

export interface Response2 {
  signaling: Signaling;
  additionalProperties?: Record<string, unknown>;
}

export const response2Schema: Schema<Response2> = lazy(() =>
  typedExpandoObject(
    { signaling: ['signaling', signalingSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
