/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ChargingLocation,
  chargingLocationSchema,
} from './chargingLocation.js';

export interface Response3 {
  destinationCharging?: ChargingLocation[];
  superchargers?: ChargingLocation[];
  timestamp?: number;
  additionalProperties?: Record<string, unknown>;
}

export const response3Schema: Schema<Response3> = lazy(() =>
  typedExpandoObject(
    {
      destinationCharging: [
        'destination_charging',
        optional(array(chargingLocationSchema)),
      ],
      superchargers: ['superchargers', optional(array(chargingLocationSchema))],
      timestamp: ['timestamp', optional(number())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
