/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Response1 {
  fleetTelemetryErrorVins: string[];
  additionalProperties?: Record<string, unknown>;
}

export const response1Schema: Schema<Response1> = typedExpandoObject(
  { fleetTelemetryErrorVins: ['fleet_telemetry_error_vins', array(string())] },
  'additionalProperties',
  optional(unknown())
);
