/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  FleetTelemetryError,
  fleetTelemetryErrorSchema,
} from './fleetTelemetryError.js';

export interface ResponseFleetTelemetryErrorsResponse {
  fleetTelemetryErrors: FleetTelemetryError[];
  additionalProperties?: Record<string, unknown>;
}

export const responseFleetTelemetryErrorsResponseSchema: Schema<ResponseFleetTelemetryErrorsResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        fleetTelemetryErrors: [
          'fleet_telemetry_errors',
          array(fleetTelemetryErrorSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
