/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ResponseRegisterPartnerResponse {
  clientId: string;
  name: string;
  description?: string;
  domain: string;
  ca?: string | null;
  createdAt: string;
  updatedAt: string;
  enterpriseTier: string;
  accountId: string;
  issuer?: string | null;
  csr?: string | null;
  csrUpdatedAt?: string | null;
  publicKey: string;
  publicKeyHash: string;
  additionalProperties?: Record<string, unknown>;
}

export const responseRegisterPartnerResponseSchema: Schema<ResponseRegisterPartnerResponse> = typedExpandoObject(
  {
    clientId: ['client_id', string()],
    name: ['name', string()],
    description: ['description', optional(string())],
    domain: ['domain', string()],
    ca: ['ca', optional(nullable(string()))],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    enterpriseTier: ['enterprise_tier', string()],
    accountId: ['account_id', string()],
    issuer: ['issuer', optional(nullable(string()))],
    csr: ['csr', optional(nullable(string()))],
    csrUpdatedAt: ['csr_updated_at', optional(nullable(string()))],
    publicKey: ['public_key', string()],
    publicKeyHash: ['public_key_hash', string()],
  },
  'additionalProperties',
  optional(unknown())
);
