/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Event, eventSchema } from './event.js';

export interface ResponseCalendarHistoryResponse {
  events: Event[];
  totalEvents: number;
  additionalProperties?: Record<string, unknown>;
}

export const responseCalendarHistoryResponseSchema: Schema<ResponseCalendarHistoryResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        events: ['events', array(eventSchema)],
        totalEvents: ['total_events', number()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
