/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Signaling {
  enabled: boolean;
  subscribeConnectivity: boolean;
  useAuthToken: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const signalingSchema: Schema<Signaling> = typedExpandoObject(
  {
    enabled: ['enabled', boolean()],
    subscribeConnectivity: ['subscribe_connectivity', boolean()],
    useAuthToken: ['use_auth_token', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
