/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SimpleOkResponse {
  response?: string;
  additionalProperties?: Record<string, unknown>;
}

export const simpleOkResponseSchema: Schema<SimpleOkResponse> = typedExpandoObject(
  { response: ['response', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
