/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';

export interface SiteInfoResponse {
  response?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const siteInfoResponseSchema: Schema<SiteInfoResponse> = typedExpandoObject(
  { response: ['response', optional(unknown())] },
  'additionalProperties',
  optional(unknown())
);
