/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface StormModeRequest {
  enabled: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const stormModeRequestSchema: Schema<StormModeRequest> = typedExpandoObject(
  { enabled: ['enabled', boolean()] },
  'additionalProperties',
  optional(unknown())
);
