/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TariffElement, tariffElementSchema } from './tariffElement.js';

export interface Tariffs {
  currency?: string;
  elements?: TariffElement[];
  additionalProperties?: Record<string, unknown>;
}

export const tariffsSchema: Schema<Tariffs> = lazy(() =>
  typedExpandoObject(
    {
      currency: ['currency', optional(string())],
      elements: ['elements', optional(array(tariffElementSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
