/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PriceComponent, priceComponentSchema } from './priceComponent.js';

export interface TariffElement {
  priceComponents?: PriceComponent[];
  restrictions?: Record<string, unknown>;
  additionalProperties?: Record<string, unknown>;
}

export const tariffElementSchema: Schema<TariffElement> = lazy(() =>
  typedExpandoObject(
    {
      priceComponents: [
        'price_components',
        optional(array(priceComponentSchema)),
      ],
      restrictions: ['restrictions', optional(dict(unknown()))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
