/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TouSettings, touSettingsSchema } from './touSettings.js';

export interface TimeOfUseSettingsRequest {
  touSettings: TouSettings;
  additionalProperties?: Record<string, unknown>;
}

export const timeOfUseSettingsRequestSchema: Schema<TimeOfUseSettingsRequest> = lazy(
  () =>
    typedExpandoObject(
      { touSettings: ['tou_settings', touSettingsSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
