/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TotalCost {
  exclVat?: number;
  inclVat?: number;
  vat?: number;
  additionalProperties?: Record<string, unknown>;
}

export const totalCostSchema: Schema<TotalCost> = typedExpandoObject(
  {
    exclVat: ['excl_vat', optional(number())],
    inclVat: ['incl_vat', optional(number())],
    vat: ['vat', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
