/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';

export interface TouSettings {
  tariffContentV2?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const touSettingsSchema: Schema<TouSettings> = typedExpandoObject(
  { tariffContentV2: ['tariff_content_v2', optional(unknown())] },
  'additionalProperties',
  optional(unknown())
);
