/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface VehicleBase {
  id?: number;
  vehicleId?: number;
  vin?: string;
  displayName?: string;
  accessType?: string;
  state?: string;
  inService?: boolean;
  calendarEnabled?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const vehicleBaseSchema: Schema<VehicleBase> = typedExpandoObject(
  {
    id: ['id', optional(number())],
    vehicleId: ['vehicle_id', optional(number())],
    vin: ['vin', optional(string())],
    displayName: ['display_name', optional(string())],
    accessType: ['access_type', optional(string())],
    state: ['state', optional(string())],
    inService: ['in_service', optional(boolean())],
    calendarEnabled: ['calendar_enabled', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
