/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface VehicleOption {
  code?: string;
  displayName?: string;
  colorCode?: string | null;
  isActive?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const vehicleOptionSchema: Schema<VehicleOption> = typedExpandoObject(
  {
    code: ['code', optional(string())],
    displayName: ['displayName', optional(string())],
    colorCode: ['colorCode', optional(nullable(string()))],
    isActive: ['isActive', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
