/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface WarrantyItem {
  warrantyType?: string;
  warrantyDisplayName?: string;
  expirationDate?: string;
  expirationOdometer?: number;
  odometerUnit?: string;
  warrantyExpiredOn?: string | null;
  coverageAgeInYears?: number;
  additionalProperties?: Record<string, unknown>;
}

export const warrantyItemSchema: Schema<WarrantyItem> = typedExpandoObject(
  {
    warrantyType: ['warrantyType', optional(string())],
    warrantyDisplayName: ['warrantyDisplayName', optional(string())],
    expirationDate: ['expirationDate', optional(string())],
    expirationOdometer: ['expirationOdometer', optional(number())],
    odometerUnit: ['odometerUnit', optional(string())],
    warrantyExpiredOn: ['warrantyExpiredOn', optional(nullable(string()))],
    coverageAgeInYears: ['coverageAgeInYears', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
