/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for WhichTrunk
 */
export enum WhichTrunk {
  Front = 'front',
  Rear = 'rear',
}

/**
 * Schema for WhichTrunk
 */
export const whichTrunkSchema: Schema<WhichTrunk> = stringEnum(
  WhichTrunk,
  true
);
