/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  accessTokenAuthenticationProvider,
  compositeAuthenticationProvider,
  OAuthConfiguration,
  requestAuthenticationProvider,
} from './authentication.js';
import { Configuration } from './configuration.js';
import { OAuthToken } from './models/oAuthToken.js';
import { ThirdpartytokenManager } from './thirdpartytokenManager.js';

export function createAuthProviderFromConfig(
  config: Partial<Configuration>,
  thirdpartytoken: () => ThirdpartytokenManager | undefined
) {
  const authConfig = {
    bearerAuth:
      config.bearerAuthCredentials &&
      accessTokenAuthenticationProvider(config.bearerAuthCredentials),
    thirdpartytoken:
      config.thirdpartytokenCredentials &&
      requestAuthenticationProvider(
        config.thirdpartytokenCredentials.oAuthToken,
        thirdpartytokenTokenProvider(
          thirdpartytoken,
          config.thirdpartytokenCredentials.oAuthTokenProvider
        ),
        config.thirdpartytokenCredentials.oAuthOnTokenUpdate,
        {
          clockSkew: config.thirdpartytokenCredentials.oAuthClockSkew,
        } as OAuthConfiguration
      ),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}

function thirdpartytokenTokenProvider(
  thirdpartytoken: () => ThirdpartytokenManager | undefined,
  defaultProvider:
    | ((
        lastOAuthToken: OAuthToken | undefined,
        authManager: ThirdpartytokenManager
      ) => Promise<OAuthToken>)
    | undefined
): ((token: OAuthToken | undefined) => Promise<OAuthToken>) | undefined {
  return (token: OAuthToken | undefined) => {
    const manager = thirdpartytoken();
    if (manager === undefined) {
      throw Error('Unable to find the OAuthManager instance');
    }
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}
