/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  accessTokenAuthenticationProvider,
  compositeAuthenticationProvider,
  OAuthConfiguration,
  requestAuthenticationProvider,
} from './authentication.js';
import { Configuration } from './configuration.js';
import { OAuthToken } from './models/oAuthToken.js';
import { Oauth2Manager } from './oauth2Manager.js';

export function createAuthProviderFromConfig(
  config: Partial<Configuration>,
  oauth2: () => Oauth2Manager | undefined
) {
  const authConfig = {
    bearerAuth:
      config.bearerAuthCredentials &&
      accessTokenAuthenticationProvider(config.bearerAuthCredentials),
    oauth2:
      config.oauth2Credentials &&
      requestAuthenticationProvider(
        config.oauth2Credentials.oAuthToken,
        oauth2TokenProvider(
          oauth2,
          config.oauth2Credentials.oAuthTokenProvider
        ),
        config.oauth2Credentials.oAuthOnTokenUpdate,
        {
          clockSkew: config.oauth2Credentials.oAuthClockSkew,
        } as OAuthConfiguration
      ),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}

function oauth2TokenProvider(
  oauth2: () => Oauth2Manager | undefined,
  defaultProvider:
    | ((
        lastOAuthToken: OAuthToken | undefined,
        authManager: Oauth2Manager
      ) => Promise<OAuthToken>)
    | undefined
): ((token: OAuthToken | undefined) => Promise<OAuthToken>) | undefined {
  return (token: OAuthToken | undefined) => {
    const manager = oauth2();
    if (manager === undefined) {
      throw Error('Unable to find the OAuthManager instance');
    }
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}
