/**
 * Tesla Fleet Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  accessTokenAuthenticationProvider,
  compositeAuthenticationProvider,
  OAuthConfiguration,
  requestAuthenticationProvider,
} from './authentication.js';
import { Configuration } from './configuration.js';
import { OauthToken } from './models/oauthToken.js';
import { Oauth2Manager } from './oauth2Manager.js';

export function createAuthProviderFromConfig(
  config: Partial<Configuration>,
  oauth2: () => Oauth2Manager | undefined
) {
  const authConfig = {
    bearerAuth:
      config.bearerAuthCredentials &&
      accessTokenAuthenticationProvider(config.bearerAuthCredentials),
    oauth2:
      config.oauth2Credentials &&
      requestAuthenticationProvider(
        config.oauth2Credentials.oauthToken,
        oauth2TokenProvider(
          oauth2,
          config.oauth2Credentials.oauthTokenProvider
        ),
        config.oauth2Credentials.oauthOnTokenUpdate,
        {
          clockSkew: config.oauth2Credentials.oauthClockSkew,
        } as OAuthConfiguration
      ),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}

function oauth2TokenProvider(
  oauth2: () => Oauth2Manager | undefined,
  defaultProvider:
    | ((
        lastOAuthToken: OauthToken | undefined,
        authManager: Oauth2Manager
      ) => Promise<OauthToken>)
    | undefined
): ((token: OauthToken | undefined) => Promise<OauthToken>) | undefined {
  return (token: OauthToken | undefined) => {
    const manager = oauth2();
    if (manager === undefined) {
      throw Error('Unable to find the OAuthManager instance');
    }
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}
